# Generated by Django 4.1.7 on 2023-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_event_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="logo",
            field=models.ImageField(upload_to="logo"),
        ),
    ]
