# Generated by Django 4.2 on 2023-04-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_event_participantd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="participantd",
            new_name="participants",
        ),
    ]
